from database.connection import db
from models.roadmap import Roadmap, RoadmapItem
from models.profile import Profile
from services.profile_service import ProfileService
from services.gemini_service import GeminiService

class RoadmapService:
    @staticmethod
    def get_roadmaps(user_id):
        """Retrieves all roadmaps for a user, including progress items."""
        roadmaps = Roadmap.query.filter_by(user_id=user_id).all()
        return {"roadmaps": [rm.to_dict() for rm in roadmaps], "status": 200}

    @staticmethod
    def create_roadmap(user_id, title, target_role, description=None):
        """Creates a new learning/career roadmap, seeding items generated by Gemini AI."""
        if not title:
            return {"error": "Roadmap title is required", "status": 400}
        if not target_role:
            return {"error": "Target role is required to generate roadmap items", "status": 400}

        try:
            # Fetch candidate details
            profile = Profile.query.filter_by(user_id=user_id).first()
            experience_level = profile.experience_level if profile and profile.experience_level else "Entry"

            # Create the Roadmap container
            new_roadmap = Roadmap(
                user_id=user_id,
                title=title,
                target_role=target_role,
                description=description
            )
            db.session.add(new_roadmap)
            db.session.flush() # Secure roadmap ID

            # Generate roadmap milestones using Gemini API
            ai_data = GeminiService.generate_roadmap(target_role, experience_level)
            
            # Extract roadmap items from AI output, fallback to default static generator if failed
            items_list = ai_data.get('items', []) if ai_data else []
            if not items_list:
                items_list = RoadmapService._generate_default_items(target_role)

            for index, item_data in enumerate(items_list):
                item = RoadmapItem(
                    roadmap_id=new_roadmap.id,
                    title=item_data['title'],
                    description=item_data['description'],
                    status='pending',
                    order_index=item_data.get('order_index', index + 1)
                )
                db.session.add(item)

            db.session.commit()

            # Recalculate profile readiness
            ProfileService.recalculate_readiness_score(user_id)

            return {
                "message": "Roadmap created and seeded successfully using Gemini AI.",
                "roadmap": new_roadmap.to_dict(),
                "status": 201
            }
        except Exception as e:
            db.session.rollback()
            return {"error": f"Failed to create roadmap: {str(e)}", "status": 500}


    @staticmethod
    def update_item_status(user_id, item_id, status):
        """Updates the status of a specific roadmap item."""
        if status not in ['pending', 'in_progress', 'completed']:
            return {"error": "Status must be 'pending', 'in_progress', or 'completed'", "status": 400}

        # Query the item and verify owner through joins
        item = RoadmapItem.query.join(Roadmap).filter(
            RoadmapItem.id == item_id,
            Roadmap.user_id == user_id
        ).first()

        if not item:
            return {"error": "Roadmap item not found or access denied", "status": 404}

        try:
            item.status = status
            db.session.commit()

            # Recalculate profile readiness
            ProfileService.recalculate_readiness_score(user_id)

            return {
                "message": "Roadmap item updated successfully",
                "item": item.to_dict(),
                "status": 200
            }
        except Exception as e:
            db.session.rollback()
            return {"error": f"Failed to update roadmap item: {str(e)}", "status": 500}

    @staticmethod
    def _generate_default_items(target_role):
        """Helper to return list of milestone items based on target job role."""
        role_lower = target_role.lower()
        
        frontend_milestones = [
            {"title": "HTML, CSS & Web Layouts", "description": "Master responsive web design, Flexbox, CSS Grid, and semantic structure."},
            {"title": "JavaScript Fundamentals", "description": "Learn ES6+ syntax, asynchronous programming, APIs, and DOM manipulation."},
            {"title": "ReactJS or Frontend Frameworks", "description": "Understand components, hooks, state management (Redux/Context), and client-side routing."},
            {"title": "Git & Deployment Workflows", "description": "Learn version control, pull requests, and deploy frontend projects to platforms like Vercel/Netlify."},
            {"title": "Mock Interviews & Portfolio Construction", "description": "Build modern frontend portfolio apps, optimize Github profiles, and review mock CSS/JS questions."}
        ]

        backend_milestones = [
            {"title": "Programming Language Proficiency", "description": "Master basic structures and intermediate concepts in Python, Java, Node.js or Go."},
            {"title": "Database Schema Design & SQL", "description": "Learn relational database design, indexing, foreign keys, and write optimized SQL queries."},
            {"title": "REST API Development", "description": "Implement authentication, middleware, request parsing, and response structures in Flask, Express, or Spring Boot."},
            {"title": "System Design & Architecture", "description": "Understand MVC architecture, ORMs, caching layers (Redis), and basic application scaling patterns."},
            {"title": "Testing & Deployment (Docker)", "description": "Write integration tests, build docker images, and review backend/OOP mock interview questions."}
        ]

        data_science_milestones = [
            {"title": "Python & Data Processing", "description": "Learn Pandas, NumPy, and clean raw dataset pipelines."},
            {"title": "Mathematics & Applied Statistics", "description": "Review probability theory, descriptive statistics, and linear algebra foundations."},
            {"title": "Machine Learning Fundamentals", "description": "Train classification, regression, and clustering algorithms using Scikit-Learn."},
            {"title": "Data Visualization & Communication", "description": "Build interactive plots using Matplotlib, Seaborn, and explain technical insights to non-tech audiences."},
            {"title": "SQL for Analytics & Portfolio Project", "description": "Perform complex database joins, query data warehouses, and build an end-to-end ML model showcase."}
        ]

        generic_milestones = [
            {"title": "Core Technical Prep", "description": "Practice Data Structures and Algorithms (Arrays, HashMaps, Trees, Graphs) on LeetCode/Hackerrank."},
            {"title": "Project Showcasing", "description": "Create or refine at least two major projects with high-quality README files and active deployments."},
            {"title": "Resume & LinkedIn Branding", "description": "Format resume utilizing STAR methodology and keywords relevant to target positions."},
            {"title": "Behavioral Interview Prep", "description": "Draft STAR method responses for teamwork, conflict resolution, leadership, and technical failures."},
            {"title": "Job Searching & Mock Interviews", "description": "Apply via cold emailing, referrals, and practice live mock whiteboard interviews."}
        ]

        if "front" in role_lower:
            return frontend_milestones
        elif "back" in role_lower or "api" in role_lower:
            return backend_milestones
        elif "data" in role_lower or "machine" in role_lower or "ml" in role_lower:
            return data_science_milestones
        else:
            return generic_milestones
